CREATE TABLE IF NOT EXISTS expenses (
  id        SERIAL PRIMARY KEY,
  label     VARCHAR(255) NOT NULL,
  amount    NUMERIC(10, 2) NOT NULL,
  category  VARCHAR(100) NOT NULL,
  date      DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMP DEFAULT NOW()
);
